// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package confproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestId struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Album                string   `protobuf:"bytes,2,opt,name=album,proto3" json:"album,omitempty"`
	Year                 string   `protobuf:"bytes,3,opt,name=year,proto3" json:"year,omitempty"`
	Rank                 string   `protobuf:"bytes,4,opt,name=rank,proto3" json:"rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestId) Reset()         { *m = RequestId{} }
func (m *RequestId) String() string { return proto.CompactTextString(m) }
func (*RequestId) ProtoMessage()    {}
func (*RequestId) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *RequestId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestId.Unmarshal(m, b)
}
func (m *RequestId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestId.Marshal(b, m, deterministic)
}
func (m *RequestId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestId.Merge(m, src)
}
func (m *RequestId) XXX_Size() int {
	return xxx_messageInfo_RequestId.Size(m)
}
func (m *RequestId) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestId.DiscardUnknown(m)
}

var xxx_messageInfo_RequestId proto.InternalMessageInfo

func (m *RequestId) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RequestId) GetAlbum() string {
	if m != nil {
		return m.Album
	}
	return ""
}

func (m *RequestId) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *RequestId) GetRank() string {
	if m != nil {
		return m.Rank
	}
	return ""
}

type ReplyInfo struct {
	Info                 string   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyInfo) Reset()         { *m = ReplyInfo{} }
func (m *ReplyInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyInfo) ProtoMessage()    {}
func (*ReplyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *ReplyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyInfo.Unmarshal(m, b)
}
func (m *ReplyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyInfo.Marshal(b, m, deterministic)
}
func (m *ReplyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyInfo.Merge(m, src)
}
func (m *ReplyInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyInfo.Size(m)
}
func (m *ReplyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyInfo proto.InternalMessageInfo

func (m *ReplyInfo) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestId)(nil), "confproto.requestId")
	proto.RegisterType((*ReplyInfo)(nil), "confproto.replyInfo")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0xce, 0xcf, 0x4b, 0x03, 0x33,
	0x95, 0x62, 0xb9, 0x38, 0x8b, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x3c, 0x53, 0x84, 0x84, 0xb8,
	0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x11,
	0x2e, 0xd6, 0xc4, 0x9c, 0xa4, 0xd2, 0x5c, 0x09, 0x26, 0xb0, 0x20, 0x84, 0x03, 0x52, 0x59, 0x99,
	0x9a, 0x58, 0x24, 0xc1, 0x0c, 0x51, 0x09, 0x62, 0x83, 0xc4, 0x8a, 0x12, 0xf3, 0xb2, 0x25, 0x58,
	0x20, 0x62, 0x20, 0xb6, 0x92, 0x3c, 0xc8, 0xf8, 0x82, 0x9c, 0x4a, 0xcf, 0xbc, 0xb4, 0x7c, 0x90,
	0x82, 0xcc, 0xbc, 0xb4, 0x7c, 0x98, 0xf1, 0x20, 0xb6, 0x91, 0x2b, 0x17, 0x7b, 0x7a, 0x6a, 0x09,
	0x58, 0xda, 0x8a, 0x8b, 0xab, 0x28, 0xb5, 0xa4, 0xb4, 0x28, 0x0f, 0xcc, 0x13, 0xd1, 0x83, 0x3b,
	0x52, 0x0f, 0xee, 0x42, 0x29, 0x54, 0x51, 0xa8, 0xc1, 0x4a, 0x0c, 0x4e, 0x7c, 0x51, 0x3c, 0x7a,
	0xfa, 0xd6, 0x70, 0xb9, 0x24, 0x36, 0x30, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x3a,
	0xb8, 0x57, 0xf8, 0x00, 0x00, 0x00,
}
