server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /tiempor {
        rewrite ^/tiempor(.*) /$1 break;
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /tiempohis {
        rewrite ^/tiempohis(.*) /$1 break;
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://backend:8080;
    }

    location /tiempor/ram {
        proxy_pass http://backend:8080/tiempor/ram;
    }

    location /tiempor/cpu {
        proxy_pass http://backend:8080/tiempor/cpu;
    }

    location /tiempohis/ram {
        proxy_pass http://backend:8080/tiempohis/ram;
    }

    location /tiempohis/cpu {
        proxy_pass http://backend:8080/tiempohis/cpu;
    }

}