apiVersion: v1
kind: Secret
metadata:
  name: secret-env-consumer
  namespace: kafka
type: Opaque
data:
  PORT : 'MzAwMA==' 
  KAFKA_BROKERS : 'bXktY2x1c3Rlci1rYWZrYS1ib290c3RyYXA6OTA5Mg=='
  KAFKA_TOPIC : 'dG9waWMtc29wZXMx' 
